# Generated by Django 3.2.2 on 2021-06-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.PositiveSmallIntegerField(choices=[(0, 'spade'), (1, 'club'), (2, 'diamond'), (3, 'heart')], default=0)),
                ('rank', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deckType', models.CharField(default='', max_length=10)),
                ('imageFormat', models.CharField(default='', max_length=4)),
                ('cardbackType', models.CharField(default='', max_length=10)),
                ('cardbackColor', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
