# Generated by Django 3.2.2 on 2021-06-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makedecks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.CharField(default='ace', max_length=5),
        ),
    ]
