# Generated by Django 3.2.2 on 2021-06-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makedecks', '0002_alter_card_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deckType',
            field=models.CharField(choices=[('ST', 'Standard Poker Deck'), ('SH', 'Sheepshead Deck'), ('PI', 'Pinochle Deck')], default='STANDARD', max_length=2),
        ),
    ]
