# Generated by Django 3.2.2 on 2021-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makedecks', '0004_alter_deck_decktype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.IntegerField(choices=[(14, 'Ace'), (2, 'Deuce'), (3, 'Trey'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten'), (11, 'Jack'), (12, 'Queen'), (13, 'King')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.IntegerField(choices=[(0, 'Spade'), (1, 'Club'), (2, 'Diamond'), (3, 'Heart')]),
        ),
    ]
