# Generated by Django 3.2.2 on 2021-06-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makedecks', '0005_auto_20210619_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
