# Generated by Django 3.2.2 on 2021-06-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_card_wager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Screen_Name',
            field=models.CharField(default='Choose a Screen Name', max_length=16, primary_key=True, serialize=False),
        ),
    ]
